security:
  user:
    name: pufik
    password: pufikpass

spring:
  datasource:
    name: pufikidb
  #    username: pufik
  #    password: pufikpass
  jpa:
    show-sql: true
  data:
    rest:
      base-path: /api

logging:
  level:
    root: info

---
spring:
  profiles: prod

  datasource:
    url: jdbc:postgresql://ec2-50-17-246-114.compute-1.amazonaws.com:5432/d9tnf8ll5pss9c
    username: topvkufwauqnow
    password: 2d3cc60efb4eb3d21af969c65044409f146850c780f16261fac481408e23a6cb
    driver-class-name: org.postgresql.Driver
    platform: postgres
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    maxActive: 10
    removeAbandoned: true

  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create-drop


logging:
  level:
    ru.digitalsuperhero.dshapi: info
    root: warn